name = "press_utils"
description = ""
version = "0.1.0-dev"

authors = ["Matheus Xavier"]
maintainers = ["Matheus Xavier <soft.song@fastmail.net>"]
maintainers-logins = ["xadaemon"]
licenses = "Apache-2.0"
website = "https://github.com/stateprisma/pr_utils"
tags = ["utils", "argparse"]
