name = "argparse_example"
description = ""
version = "0.1.0-dev"

authors = ["Matheus Xavier"]
maintainers = ["Matheus Xavier <soft.song@fastmail.net>"]
maintainers-logins = ["xadaemon"]
licenses = "Apache-2.0"
website = ""
tags = []

executables = ["argparse_example"]
